name: MMSP JPEG Project CI

# 觸發條件：當 push 到 main 分支時執行
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # 1. 下載你的程式碼
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 安裝必要的工具 (curl, gcc 通常 ubuntu 都有，但確保一下)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc curl

    # 3. 賦予腳本執行權限並執行 Workflow
    # 這一步會下載圖片、編譯、執行 Mode 0~3、並進行 cmp 比對
    - name: Run Workflow Script
      run: |
        chmod +x workflow.sh
        ./workflow.sh

    # 4. 【關鍵步驟】上傳 Artifacts
    # 這裡就是教授要的：把重要的產出物打包留存
    - name: Upload Artifacts (Results)
      if: always()  # 即使上面測試失敗(cmp fail)，也要上傳目前的產出物以便除錯
      uses: actions/upload-artifact@v4
      with:
        name: JPEG-Project-Outputs
        path: |
          *.bmp
          *.bin
          *.txt
          *.raw
          encoder
          decoder
          # 不需要上傳 *.c 或 .h，因為原始碼已經在 repo 裡了
